version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # - sudo apt install zip
      - cd $CODEBUILD_SRC_DIR_app
      - pip install -r requirements-dev.txt
      - mkdir artifacts
      - cd artifacts
      - zip -j registry.zip ../functions/registry/*;
      - zip -j inference_tracking.zip ../functions/inference_tracking/*;
      - zip -j sfn_end.zip ../functions/sfn_end/*;
      - cd ../functions/inference
      - pip install -r requirements.txt --target .
      - zip -r $CODEBUILD_SRC_DIR_app/artifacts/inference.zip *
artifacts:
  base-directory: $CODEBUILD_SRC_DIR_app/artifacts
  files:
    - '**/*'


#wget https://raw.githubusercontent.com/Kerem-Sami-Coop/caishen-lambda/develop/lambda/initial_load.py
#Use $etc to use set branches etc
#zip -j initial_load.zip initial_load.py